
export const CLEAR = "CLEAR"
export const LOCK = "LOCK"
export const UNLOCK = "UNLOCK"

export const EXAMPLE_PENDING = "EXAMPLE_PENDING"
export const EXAMPLE_SUCCESS = "EXAMPLE_SUCCESS"
export const EXAMPLE_FAIL = "EXAMPLE_FAIL"


export const EMPLOYEES_PENDING = "EMPLOYEES_PENDING"
export const EMPLOYEES_SUCCESS = "EMPLOYEES_SUCCESS"
export const EMPLOYEES_FAIL = "EMPLOYEES_FAIL"

